
"""
Returned when the userActivated subcription triggers.
"""
type UserActivatedResult {
  activated: Boolean!
  activated_by: User
  comments: String
}

extend type Subscription {
  """
  Emitted when the user is first activated. If a subscription is attempted after the User is already active an error
  will be returned.
  """
  userActivated(userId: ID!): UserActivatedResult!

  """
  Emitted when a user registers. This can be used to listen for new users joining Response or to notify when a user
  needs activation by looking at the `is_activated` attribute for the User.
  """
  userRegistered: User!
}