// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
	"github.com/responserms/server/ent/authsession"
)

// AuthSession is the model entity for the AuthSession schema.
type AuthSession struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthSession) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case authsession.FieldID:
			values[i] = &sql.NullInt64{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type AuthSession", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthSession fields.
func (as *AuthSession) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			as.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this AuthSession.
// Note that, you need to call AuthSession.Unwrap() before calling this method, if this AuthSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (as *AuthSession) Update() *AuthSessionUpdateOne {
	return (&AuthSessionClient{config: as.config}).UpdateOne(as)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (as *AuthSession) Unwrap() *AuthSession {
	tx, ok := as.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthSession is not a transactional entity")
	}
	as.config.driver = tx.drv
	return as
}

// String implements the fmt.Stringer.
func (as *AuthSession) String() string {
	var builder strings.Builder
	builder.WriteString("AuthSession(")
	builder.WriteString(fmt.Sprintf("id=%v", as.ID))
	builder.WriteByte(')')
	return builder.String()
}

// AuthSessions is a parsable slice of AuthSession.
type AuthSessions []*AuthSession

func (as AuthSessions) config(cfg config) {
	for _i := range as {
		as[_i].config = cfg
	}
}
