// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/responserms/server/ent/maptype"
	"github.com/responserms/server/ent/predicate"
)

// MapTypeDelete is the builder for deleting a MapType entity.
type MapTypeDelete struct {
	config
	hooks    []Hook
	mutation *MapTypeMutation
}

// Where adds a new predicate to the delete builder.
func (mtd *MapTypeDelete) Where(ps ...predicate.MapType) *MapTypeDelete {
	mtd.mutation.predicates = append(mtd.mutation.predicates, ps...)
	return mtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mtd *MapTypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mtd.hooks) == 0 {
		affected, err = mtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MapTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mtd.mutation = mutation
			affected, err = mtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mtd.hooks) - 1; i >= 0; i-- {
			mut = mtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtd *MapTypeDelete) ExecX(ctx context.Context) int {
	n, err := mtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mtd *MapTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: maptype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: maptype.FieldID,
			},
		},
	}
	if ps := mtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mtd.driver, _spec)
}

// MapTypeDeleteOne is the builder for deleting a single MapType entity.
type MapTypeDeleteOne struct {
	mtd *MapTypeDelete
}

// Exec executes the deletion query.
func (mtdo *MapTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := mtdo.mtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{maptype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mtdo *MapTypeDeleteOne) ExecX(ctx context.Context) {
	mtdo.mtd.ExecX(ctx)
}
