// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/responserms/server/ent/metadata"
	"github.com/responserms/server/ent/player"
	"github.com/responserms/server/ent/playeridentifier"
	"github.com/responserms/server/ent/server"
	"github.com/responserms/server/ent/user"
)

// PlayerCreate is the builder for creating a Player entity.
type PlayerCreate struct {
	config
	mutation *PlayerMutation
	hooks    []Hook
}

// SetCreatedAt sets the created_at field.
func (pc *PlayerCreate) SetCreatedAt(t time.Time) *PlayerCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (pc *PlayerCreate) SetNillableCreatedAt(t *time.Time) *PlayerCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the updated_at field.
func (pc *PlayerCreate) SetUpdatedAt(t time.Time) *PlayerCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (pc *PlayerCreate) SetNillableUpdatedAt(t *time.Time) *PlayerCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetName sets the name field.
func (pc *PlayerCreate) SetName(s string) *PlayerCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetTotalMinutes sets the total_minutes field.
func (pc *PlayerCreate) SetTotalMinutes(i int) *PlayerCreate {
	pc.mutation.SetTotalMinutes(i)
	return pc
}

// SetNillableTotalMinutes sets the total_minutes field if the given value is not nil.
func (pc *PlayerCreate) SetNillableTotalMinutes(i *int) *PlayerCreate {
	if i != nil {
		pc.SetTotalMinutes(*i)
	}
	return pc
}

// SetSessionStartedAt sets the session_started_at field.
func (pc *PlayerCreate) SetSessionStartedAt(t time.Time) *PlayerCreate {
	pc.mutation.SetSessionStartedAt(t)
	return pc
}

// SetNillableSessionStartedAt sets the session_started_at field if the given value is not nil.
func (pc *PlayerCreate) SetNillableSessionStartedAt(t *time.Time) *PlayerCreate {
	if t != nil {
		pc.SetSessionStartedAt(*t)
	}
	return pc
}

// SetSessionEndedAt sets the session_ended_at field.
func (pc *PlayerCreate) SetSessionEndedAt(t time.Time) *PlayerCreate {
	pc.mutation.SetSessionEndedAt(t)
	return pc
}

// SetNillableSessionEndedAt sets the session_ended_at field if the given value is not nil.
func (pc *PlayerCreate) SetNillableSessionEndedAt(t *time.Time) *PlayerCreate {
	if t != nil {
		pc.SetSessionEndedAt(*t)
	}
	return pc
}

// SetLastSeenAt sets the last_seen_at field.
func (pc *PlayerCreate) SetLastSeenAt(t time.Time) *PlayerCreate {
	pc.mutation.SetLastSeenAt(t)
	return pc
}

// SetNillableLastSeenAt sets the last_seen_at field if the given value is not nil.
func (pc *PlayerCreate) SetNillableLastSeenAt(t *time.Time) *PlayerCreate {
	if t != nil {
		pc.SetLastSeenAt(*t)
	}
	return pc
}

// SetMetadataID sets the metadata edge to Metadata by id.
func (pc *PlayerCreate) SetMetadataID(id int) *PlayerCreate {
	pc.mutation.SetMetadataID(id)
	return pc
}

// SetNillableMetadataID sets the metadata edge to Metadata by id if the given value is not nil.
func (pc *PlayerCreate) SetNillableMetadataID(id *int) *PlayerCreate {
	if id != nil {
		pc = pc.SetMetadataID(*id)
	}
	return pc
}

// SetMetadata sets the metadata edge to Metadata.
func (pc *PlayerCreate) SetMetadata(m *Metadata) *PlayerCreate {
	return pc.SetMetadataID(m.ID)
}

// AddServerIDs adds the servers edge to Server by ids.
func (pc *PlayerCreate) AddServerIDs(ids ...int) *PlayerCreate {
	pc.mutation.AddServerIDs(ids...)
	return pc
}

// AddServers adds the servers edges to Server.
func (pc *PlayerCreate) AddServers(s ...*Server) *PlayerCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pc.AddServerIDs(ids...)
}

// SetUserID sets the user edge to User by id.
func (pc *PlayerCreate) SetUserID(id int) *PlayerCreate {
	pc.mutation.SetUserID(id)
	return pc
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (pc *PlayerCreate) SetNillableUserID(id *int) *PlayerCreate {
	if id != nil {
		pc = pc.SetUserID(*id)
	}
	return pc
}

// SetUser sets the user edge to User.
func (pc *PlayerCreate) SetUser(u *User) *PlayerCreate {
	return pc.SetUserID(u.ID)
}

// AddIdentifierIDs adds the identifiers edge to PlayerIdentifier by ids.
func (pc *PlayerCreate) AddIdentifierIDs(ids ...int) *PlayerCreate {
	pc.mutation.AddIdentifierIDs(ids...)
	return pc
}

// AddIdentifiers adds the identifiers edges to PlayerIdentifier.
func (pc *PlayerCreate) AddIdentifiers(p ...*PlayerIdentifier) *PlayerCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pc.AddIdentifierIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (pc *PlayerCreate) Mutation() *PlayerMutation {
	return pc.mutation
}

// Save creates the Player in the database.
func (pc *PlayerCreate) Save(ctx context.Context) (*Player, error) {
	var (
		err  error
		node *Player
	)
	pc.defaults()
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PlayerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PlayerCreate) SaveX(ctx context.Context) *Player {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (pc *PlayerCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := player.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := player.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pc.mutation.TotalMinutes(); !ok {
		v := player.DefaultTotalMinutes
		pc.mutation.SetTotalMinutes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PlayerCreate) check() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New("ent: missing required field \"updated_at\"")}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if _, ok := pc.mutation.TotalMinutes(); !ok {
		return &ValidationError{Name: "total_minutes", err: errors.New("ent: missing required field \"total_minutes\"")}
	}
	return nil
}

func (pc *PlayerCreate) sqlSave(ctx context.Context) (*Player, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pc *PlayerCreate) createSpec() (*Player, *sqlgraph.CreateSpec) {
	var (
		_node = &Player{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: player.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: player.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: player.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: player.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: player.FieldName,
		})
		_node.Name = value
	}
	if value, ok := pc.mutation.TotalMinutes(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: player.FieldTotalMinutes,
		})
		_node.TotalMinutes = value
	}
	if value, ok := pc.mutation.SessionStartedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: player.FieldSessionStartedAt,
		})
		_node.SessionStartedAt = &value
	}
	if value, ok := pc.mutation.SessionEndedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: player.FieldSessionEndedAt,
		})
		_node.SessionEndedAt = &value
	}
	if value, ok := pc.mutation.LastSeenAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: player.FieldLastSeenAt,
		})
		_node.LastSeenAt = &value
	}
	if nodes := pc.mutation.MetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   player.MetadataTable,
			Columns: []string{player.MetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: metadata.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.ServersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   player.ServersTable,
			Columns: player.ServersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: server.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   player.UserTable,
			Columns: []string{player.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.IdentifiersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   player.IdentifiersTable,
			Columns: []string{player.IdentifiersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: playeridentifier.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlayerCreateBulk is the builder for creating a bulk of Player entities.
type PlayerCreateBulk struct {
	config
	builders []*PlayerCreate
}

// Save creates the Player entities in the database.
func (pcb *PlayerCreateBulk) Save(ctx context.Context) ([]*Player, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Player, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (pcb *PlayerCreateBulk) SaveX(ctx context.Context) []*Player {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
