// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/responserms/server/ent/activation"
	"github.com/responserms/server/ent/maplayer"
	"github.com/responserms/server/ent/maptype"
	"github.com/responserms/server/ent/player"
	"github.com/responserms/server/ent/playeridentifier"
	"github.com/responserms/server/ent/schema"
	"github.com/responserms/server/ent/server"
	"github.com/responserms/server/ent/session"
	"github.com/responserms/server/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activationMixin := schema.Activation{}.Mixin()
	activationMixinFields0 := activationMixin[0].Fields()
	_ = activationMixinFields0
	activationFields := schema.Activation{}.Fields()
	_ = activationFields
	// activationDescCreatedAt is the schema descriptor for created_at field.
	activationDescCreatedAt := activationMixinFields0[0].Descriptor()
	// activation.DefaultCreatedAt holds the default value on creation for the created_at field.
	activation.DefaultCreatedAt = activationDescCreatedAt.Default.(func() time.Time)
	// activationDescUpdatedAt is the schema descriptor for updated_at field.
	activationDescUpdatedAt := activationMixinFields0[1].Descriptor()
	// activation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	activation.DefaultUpdatedAt = activationDescUpdatedAt.Default.(func() time.Time)
	// activation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	activation.UpdateDefaultUpdatedAt = activationDescUpdatedAt.UpdateDefault.(func() time.Time)
	maplayerMixin := schema.MapLayer{}.Mixin()
	maplayerMixinFields0 := maplayerMixin[0].Fields()
	_ = maplayerMixinFields0
	maplayerFields := schema.MapLayer{}.Fields()
	_ = maplayerFields
	// maplayerDescCreatedAt is the schema descriptor for created_at field.
	maplayerDescCreatedAt := maplayerMixinFields0[0].Descriptor()
	// maplayer.DefaultCreatedAt holds the default value on creation for the created_at field.
	maplayer.DefaultCreatedAt = maplayerDescCreatedAt.Default.(func() time.Time)
	// maplayerDescUpdatedAt is the schema descriptor for updated_at field.
	maplayerDescUpdatedAt := maplayerMixinFields0[1].Descriptor()
	// maplayer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	maplayer.DefaultUpdatedAt = maplayerDescUpdatedAt.Default.(func() time.Time)
	// maplayer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	maplayer.UpdateDefaultUpdatedAt = maplayerDescUpdatedAt.UpdateDefault.(func() time.Time)
	maptypeMixin := schema.MapType{}.Mixin()
	maptypeMixinFields0 := maptypeMixin[0].Fields()
	_ = maptypeMixinFields0
	maptypeFields := schema.MapType{}.Fields()
	_ = maptypeFields
	// maptypeDescCreatedAt is the schema descriptor for created_at field.
	maptypeDescCreatedAt := maptypeMixinFields0[0].Descriptor()
	// maptype.DefaultCreatedAt holds the default value on creation for the created_at field.
	maptype.DefaultCreatedAt = maptypeDescCreatedAt.Default.(func() time.Time)
	// maptypeDescUpdatedAt is the schema descriptor for updated_at field.
	maptypeDescUpdatedAt := maptypeMixinFields0[1].Descriptor()
	// maptype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	maptype.DefaultUpdatedAt = maptypeDescUpdatedAt.Default.(func() time.Time)
	// maptype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	maptype.UpdateDefaultUpdatedAt = maptypeDescUpdatedAt.UpdateDefault.(func() time.Time)
	playerMixin := schema.Player{}.Mixin()
	playerMixinFields0 := playerMixin[0].Fields()
	_ = playerMixinFields0
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescCreatedAt is the schema descriptor for created_at field.
	playerDescCreatedAt := playerMixinFields0[0].Descriptor()
	// player.DefaultCreatedAt holds the default value on creation for the created_at field.
	player.DefaultCreatedAt = playerDescCreatedAt.Default.(func() time.Time)
	// playerDescUpdatedAt is the schema descriptor for updated_at field.
	playerDescUpdatedAt := playerMixinFields0[1].Descriptor()
	// player.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	player.DefaultUpdatedAt = playerDescUpdatedAt.Default.(func() time.Time)
	// player.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	player.UpdateDefaultUpdatedAt = playerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// playerDescTotalMinutes is the schema descriptor for total_minutes field.
	playerDescTotalMinutes := playerFields[1].Descriptor()
	// player.DefaultTotalMinutes holds the default value on creation for the total_minutes field.
	player.DefaultTotalMinutes = playerDescTotalMinutes.Default.(int)
	playeridentifierMixin := schema.PlayerIdentifier{}.Mixin()
	playeridentifierMixinFields0 := playeridentifierMixin[0].Fields()
	_ = playeridentifierMixinFields0
	playeridentifierFields := schema.PlayerIdentifier{}.Fields()
	_ = playeridentifierFields
	// playeridentifierDescCreatedAt is the schema descriptor for created_at field.
	playeridentifierDescCreatedAt := playeridentifierMixinFields0[0].Descriptor()
	// playeridentifier.DefaultCreatedAt holds the default value on creation for the created_at field.
	playeridentifier.DefaultCreatedAt = playeridentifierDescCreatedAt.Default.(func() time.Time)
	// playeridentifierDescUpdatedAt is the schema descriptor for updated_at field.
	playeridentifierDescUpdatedAt := playeridentifierMixinFields0[1].Descriptor()
	// playeridentifier.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	playeridentifier.DefaultUpdatedAt = playeridentifierDescUpdatedAt.Default.(func() time.Time)
	// playeridentifier.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	playeridentifier.UpdateDefaultUpdatedAt = playeridentifierDescUpdatedAt.UpdateDefault.(func() time.Time)
	serverMixin := schema.Server{}.Mixin()
	serverMixinFields0 := serverMixin[0].Fields()
	_ = serverMixinFields0
	serverFields := schema.Server{}.Fields()
	_ = serverFields
	// serverDescCreatedAt is the schema descriptor for created_at field.
	serverDescCreatedAt := serverMixinFields0[0].Descriptor()
	// server.DefaultCreatedAt holds the default value on creation for the created_at field.
	server.DefaultCreatedAt = serverDescCreatedAt.Default.(func() time.Time)
	// serverDescUpdatedAt is the schema descriptor for updated_at field.
	serverDescUpdatedAt := serverMixinFields0[1].Descriptor()
	// server.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	server.DefaultUpdatedAt = serverDescUpdatedAt.Default.(func() time.Time)
	// server.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	server.UpdateDefaultUpdatedAt = serverDescUpdatedAt.UpdateDefault.(func() time.Time)
	sessionMixin := schema.Session{}.Mixin()
	sessionMixinFields0 := sessionMixin[0].Fields()
	_ = sessionMixinFields0
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreateTime is the schema descriptor for create_time field.
	sessionDescCreateTime := sessionMixinFields0[0].Descriptor()
	// session.DefaultCreateTime holds the default value on creation for the create_time field.
	session.DefaultCreateTime = sessionDescCreateTime.Default.(func() time.Time)
	// sessionDescUpdateTime is the schema descriptor for update_time field.
	sessionDescUpdateTime := sessionMixinFields0[1].Descriptor()
	// session.DefaultUpdateTime holds the default value on creation for the update_time field.
	session.DefaultUpdateTime = sessionDescUpdateTime.Default.(func() time.Time)
	// session.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	session.UpdateDefaultUpdateTime = sessionDescUpdateTime.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescIsSystem is the schema descriptor for is_system field.
	userDescIsSystem := userFields[3].Descriptor()
	// user.DefaultIsSystem holds the default value on creation for the is_system field.
	user.DefaultIsSystem = userDescIsSystem.Default.(bool)
}
