// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Activation is the predicate function for activation builders.
type Activation func(*sql.Selector)

// AuthSession is the predicate function for authsession builders.
type AuthSession func(*sql.Selector)

// MapLayer is the predicate function for maplayer builders.
type MapLayer func(*sql.Selector)

// MapType is the predicate function for maptype builders.
type MapType func(*sql.Selector)

// Metadata is the predicate function for metadata builders.
type Metadata func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// PlayerIdentifier is the predicate function for playeridentifier builders.
type PlayerIdentifier func(*sql.Selector)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)

// ServerType is the predicate function for servertype builders.
type ServerType func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
